mixed-port: 7890
allow-lan: false
mode: rule
log-level: silent
ipv6: false
external-controller: :9090
dns:
  enable: true
  default-nameserver:
    - 223.5.5.5
    - 1.0.0.1
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-filter:
    - "*.lan"
    - stun.*.*.*
    - stun.*.*
    - time.windows.com
    - time.nist.gov
    - time.apple.com
    - time.asia.apple.com
    - "*.ntp.org.cn"
    - "*.openwrt.pool.ntp.org"
    - time1.cloud.tencent.com
    - time.ustc.edu.cn
    - pool.ntp.org
    - ntp.ubuntu.com
    - ntp.aliyun.com
    - ntp1.aliyun.com
    - ntp2.aliyun.com
    - ntp3.aliyun.com
    - ntp4.aliyun.com
    - ntp5.aliyun.com
    - ntp6.aliyun.com
    - ntp7.aliyun.com
    - time1.aliyun.com
    - time2.aliyun.com
    - time3.aliyun.com
    - time4.aliyun.com
    - time5.aliyun.com
    - time6.aliyun.com
    - time7.aliyun.com
    - "*.time.edu.cn"
    - time1.apple.com
    - time2.apple.com
    - time3.apple.com
    - time4.apple.com
    - time5.apple.com
    - time6.apple.com
    - time7.apple.com
    - time1.google.com
    - time2.google.com
    - time3.google.com
    - time4.google.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "*.msftconnecttest.com"
    - "*.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - "*.*.*.srv.nintendo.net"
    - "*.*.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.ipv6.microsoft.com"
    - "*.*.xboxlive.com"
    - speedtest.cros.wr.pvp.net
  nameserver:
    - https://223.6.6.6/dns-query
    - https://rubyfish.cn/dns-query
    - https://dns.pub/dns-query
  fallback:
    - https://dns.rubyfish.cn/dns-query
    - https://public.dns.iij.jp/dns-query
    - tls://8.8.4.4
  fallback-filter:
    geoip: true
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32
      - 127.0.0.1/32
    domain:
      - +.google.com
      - +.facebook.com
      - +.twitter.com
      - +.youtube.com
      - +.xn--ngstr-lra8j.com
      - +.google.cn
      - +.googleapis.cn
      - +.googleapis.com
      - +.gvt1.com
    
proxies:
#é”šç‚¹
DY: &DY
    type: http
    url: "https://sanfen003.xyz/api/v1/client/subscribe?token=075ea7d2cdac67fc271b165426ba3dab&flag=clash"
    health-check:
      enable: true
      interval: 600
      # lazy: true
      url: http://cp.cloudflare.com/generate_204
      
   
c: &c
  type: http
  behavior: classical
  interval: 86400
  
#æ”¹ä¸‹é¢ä»£ç†æä¾›å•†çš„åå­—çš„è¯ï¼Œè¿™é‡Œé¢çš„åå­—ä¹Ÿéœ€è¦ä¸€å¹¶ä¿®æ”¹

pr: &pr
  type: select
  proxies:
    - ğŸ”— ç›´è¿
    - ğŸš€ å…¨çƒåŠ é€Ÿ
    - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
    - ğŸ‡ºğŸ‡³ å…¨çƒèŠ‚ç‚¹
    - ğŸš« æ‹¦æˆª

proxy-providers:

  HK:
    path: ./proxy_providers/HK.yaml
    filter: 'æ¸¯|é¦™æ¸¯|HK|HongKong|Hong Kong|ğŸ‡­ğŸ‡°' # golang regex string
    <<: *DY
    
  US:
    path: ./proxy_providers/US.yaml
    filter: 'ç¾|ç¾å›½|US|UnitedStates|ğŸ‡ºğŸ‡¸' # golang regex string
    <<: *DY
    
  TW:
    path: ./proxy_providers/TW.yaml
    filter: 'å°|å°æ¹¾|TW|Taiwan|ğŸ‡¹ğŸ‡¼' # golang regex string
    <<: *DY
    
  SG:
    path: ./proxy_providers/SG.yaml
    filter: 'æ–°|æ–°åŠ å¡|SG|Singapore|ç‹®åŸ|ğŸ‡¸ğŸ‡¬' # golang regex string
    <<: *DY
    
  JP:
    path: ./proxy_providers/JP.yaml
    filter: 'æ—¥æœ¬|JP|Japan|ğŸ‡¯ğŸ‡µ' # golang regex string
    <<: *DY
    
  UN:
    path: ./proxy_providers/UN.yaml
    filter: 'GB|UK' # golang regex string
    <<: *DY

proxy-groups:

  - name: ğŸš€ å…¨çƒåŠ é€Ÿ
    type: select
    proxies:
      - ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
      - ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
      - ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
      - ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
      - ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
      - ğŸ‡ºğŸ‡³ å…¨çƒèŠ‚ç‚¹
      - ğŸ”— ç›´è¿
      
#åˆ†éš”ï¼Œä¸‹é¢æ˜¯åœ°åŒºåˆ†ç»„
  - name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹
    type: select
    use:
      - HK

  - name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹
    type: select
    use:
      - TW

  - name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹
    type: select
    use:
      - JP

  - name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹
    type: select
    use:
      - US

  - name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹
    type: select
    use:
      - SG

  - name: ğŸ‡ºğŸ‡³ å…¨çƒèŠ‚ç‚¹
    type: select
    use:
      - UN

#ç¤¾äº¤
  - name: âœˆï¸ Telegram
    <<: *pr

  - name: ğŸ® Game
    <<: *pr

#æµåª’ä½“
  - name: ğŸ“º YouTube
    <<: *pr

  - name: ğŸ“º Netflix
    <<: *pr
    
  - name: ğŸ¹ Disney
    <<: *pr

  - name: ğŸ“º PrimeVideo
    <<: *pr
    
  - name: ğŸµ Spotify
    <<: *pr
    
  - name: ğŸ¶ TikTok
    <<: *pr 
  - name: ğŸµ OpenAi
    <<: *pr
    
#ç³»ç»Ÿä¹‹å®¶
  - name: â˜ï¸ Google
    <<: *pr
    
  - name: ğŸ Apple
    <<: *pr
    
  - name: ğŸ§© Microsoft
    <<: *pr

#åŸºæœ¬ä¸æ”¹
      
  - name: ğŸ‡¨ğŸ‡³ å›½å†…æµé‡
    type: select
    proxies:
      - ğŸ”— ç›´è¿
      - ğŸš€ å…¨çƒåŠ é€Ÿ
      - ğŸš« æ‹¦æˆª

  - name: ğŸ”— ç›´è¿
    type: select
    proxies:
      - DIRECT

  - name: ğŸš« æ‹¦æˆª
    type: select
    proxies:
      - REJECT
      - DIRECT
      - ğŸš€ å…¨çƒåŠ é€Ÿ

rule-providers:

  Lan:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Lan/Lan.yaml"
    path: ./ruleset/Lan.yaml

  Game:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Game/Game.yaml"
    path: ./rule_providers/Game.yaml

  Inside1:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Direct/Direct.yaml"
    path: ./ruleset/Inside1.yaml      

  ZhiHuAD:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ZhihuAds/ZhihuAds.yaml"
    path: ./ruleset/ZhiHuAD.yaml

  AD:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AdvertisingLite/AdvertisingLite.yaml"
    path: ./ruleset/ADLite.yaml

  GitHub:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GitHub/GitHub.yaml"
    path: ./rule_providers/GitHub.yaml

  Telegram:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Telegram/Telegram.yaml"
    path: ./rule_providers/Telegram.yaml
    
  NETFLIX:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Netflix/Netflix.yaml"
    path: ./rule_providers/NETFLIX.yaml
    
  Disney:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Disney/Disney.yaml"
    path: ./rule_providers/Disney.yaml  

  PrimeVideo:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/AmazonPrimeVideo/AmazonPrimeVideo.yaml"
    path: ./rule_providers/PrimeVideo.yaml   
    
  Spotify:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Spotify/Spotify.yaml"
    path: ./rule_providers/Spotify.yaml   
    
  YouTube:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTube/YouTube.yaml"
    path: ./rule_providers/YouTube.yaml
    
  YouTubeMusic:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/YouTubeMusic/YouTubeMusic.yaml"
    path: ./rule_providers/YouTubeMusic.yaml
    
  TikTok:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/TikTok/TikTok.yaml"
    path: ./rule_providers/TikTok.yaml
     
  Google:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Google/Google.yaml"
    path: ./rule_providers/Google.yaml
    
  GoogleFCM:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/GoogleFCM/GoogleFCM.yaml"
    path: ./rule_providers/GoogleFCM.yaml

  Apple:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Apple/Apple.yaml"
    path: ./rule_providers/Apple.yaml
    
  Microsoft:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Microsoft/Microsoft.yaml"
    path: ./rule_providers/Microsoft.yaml
    
  Global:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/Global/Global_Classical.yaml"
    path: ./ruleset/Global.yaml

  ChinaMax_Classical:
    <<: *c
    url: "https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Clash/ChinaMax/ChinaMax_Classical.yaml"
    path: ./ruleset/ChinaMax_Classical.yaml
    
  OpenAi:
    <<: *c
    url: "https://gist.githubusercontent.com/lovecxe/e2879785881a3304d4dafd6d4107bcfe/raw/OpenAi.yaml"
    path: ./ruleset/OpenAi.yaml
rules:
  - RULE-SET,Lan,ğŸ‡¨ğŸ‡³ å›½å†…æµé‡
  - RULE-SET,Game,ğŸ® Game
  - RULE-SET,Inside1,ğŸ‡¨ğŸ‡³ å›½å†…æµé‡
  - RULE-SET,AD,ğŸš« æ‹¦æˆª
  - RULE-SET,ZhiHuAD,ğŸš« æ‹¦æˆª
  - RULE-SET,GitHub,ğŸš€ å…¨çƒåŠ é€Ÿ
  - RULE-SET,OpenAi,ğŸµ OpenAi
  - RULE-SET,Telegram,âœˆï¸ Telegram
  - RULE-SET,NETFLIX,ğŸ“º Netflix
  - RULE-SET,Disney,ğŸ¹ Disney
  - RULE-SET,PrimeVideo,ğŸ“º PrimeVideo
  - RULE-SET,Spotify,ğŸµ Spotify
  - RULE-SET,YouTube,ğŸ“º YouTube
  - RULE-SET,YouTubeMusic,ğŸ“º YouTube
  - RULE-SET,TikTok,ğŸ¶ TikTok
  - RULE-SET,Google,â˜ï¸ Google
  - RULE-SET,GoogleFCM,â˜ï¸ Google
  - RULE-SET,Apple,ğŸ Apple
  - RULE-SET,Microsoft,ğŸ§© Microsoft
  - RULE-SET,Global,ğŸš€ å…¨çƒåŠ é€Ÿ
  - RULE-SET,ChinaMax_Classical,ğŸ‡¨ğŸ‡³ å›½å†…æµé‡
  - GEOIP,CN,ğŸ‡¨ğŸ‡³ å›½å†…æµé‡
  - MATCH,ğŸš€ å…¨çƒåŠ é€Ÿ
  
  
  
  
  

